package_install_commands:
  npm: npm install {name}@{version}
components:
  comp_hr_api:
    mode: local
    test_command: pnpm -C services/hr-api test && pnpm -C services/hr-api test:e2e
    build_command: pnpm -C services/hr-api run build
  comp_notification_worker:
    mode: local
    test_command: pnpm -C services/notification-worker test
    build_command: pnpm -C services/notification-worker run build
commands:
  test: (pnpm -C services/hr-api test && pnpm -C services/hr-api test:e2e) && (pnpm
    -C services/notification-worker test)
  build: (pnpm -C services/hr-api run build) && (pnpm -C services/notification-worker
    run build)
